spring.application.name=quick-rental
server.port=8989

spring.datasource.url=jdbc:mysql://localhost:3306/QUICKRENTAL?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver




GeneralException.EXCEPTION-MSG:Something went wrong

QuickVehicleService.CUSTOMER_NOT_FOUND: Please register to rent a vehicle.


QuickRentalApi.customer.deleted=Customer deleted successfully
QuickRentalApi.customer.registered=Customer registered successfully
quickVehicleService.customer.alreadyExists=Customer already exists with given Driving Licence No
QuickRentalApi.VEHICLE.ADDED=Vehicle added successfully


